services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: fitMeals_app
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitmeals_network

  app:
    build:
      context: .  # Set the build context to the current directory
    depends_on:
      - db
    ports:
      - "8081:8081"  # Expose the backend on the host
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fitMeals_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - fitmeals_network

networks:
  fitmeals_network:
    driver: bridge

volumes:
  postgres_data: