version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: fitMeals_app
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
